name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2  # This uses the checkout action

      # Step 2: Set up Node.js environment (if applicable)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Or the version of Node.js you're using

      # Step 3: Install dependencies (for a Node.js project)
      - name: Install dependencies
        run: npm install  # This runs the 'npm install' command

      # Step 4: Set environment variables
      - name: Set environment variables
        env:
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH: ${{ secrets.VITE_FIREBASE_AUTH }}
          VITE_FIREBASE_DATABASE: ${{ secrets.VITE_FIREBASE_DATABASE }}
          VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDERID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDERID }}
          VITE_FIREBASE_APPID: ${{ secrets.VITE_FIREBASE_APPID }}
          VITE_FIREBASE_MEASUREMENTID: ${{ secrets.VITE_FIREBASE_MEASUREMENTID }}

      # Step 5: Example deployment step (adjust to your needs)
      - name: Deploy to Firebase
        run: npm run deploy  # This runs your deploy script, or adjust it to your deployment process
